// lib/museoData.js

export const escudos = [
  {
    id: "escudo-1950",
    nombre: "",
    periodo: "1950 – 1960",
    src: "/museo/escudos/escudo_1950.png",
    alt: "Primer escudo del club",
    descripcion: "Primer escudo de la historia del club, viendose reflejado en los carnets de socios de la época más no en las camisetas.",
  },
  {
    id: "escudo-1960",
    nombre: "",
    periodo: "1960 – 1970",
    src: "/museo/escudos/escudo_1960.png",
    alt: "Escudo de los años 60",
    descripcion: "Escudo utilizado durante la década de los 60.",
  },
  {
    id: "escudo-1990",
    nombre: "",
    periodo: "1990 – 2000",
    src: "/museo/escudos/norm_1990.png",
    alt: "Escudo tipo banderín",
    descripcion: "Escudo inspirado en Estudiantes de La Plata.",
  },
  {
    id: "escudo-2001",
    nombre: "",
    periodo: "2000 – 2003",
    src: "/museo/escudos/escudo_2001.png",
    alt: "Escudo año 1999",
    descripcion: "Escudo clásico utilizado a comienzos del siglos XXI.",
  },
    {
    id: "escudo-2004",
    nombre: "",
    periodo: "2004 – 2005",
    src: "/museo/escudos/escudo_2004.png",
    alt: "Escudo año 2004",
    descripcion: "Escudo presente durante un par de años en el club.",
  },
  {
    id: "escudo-2010",
    nombre: "",
    periodo: "2006 – 2012",
    src: "/museo/escudos/norm_2010.png",
    alt: "Escudo insignia",
    descripcion: "Escudo utilizado durante casi una década, acompañó grandes momentos y acontecimientos.",
  },
  {
    id: "escudo-2015",
    nombre: "",
    periodo: "2012 – 2019",
    src: "/museo/escudos/norm_2012.png",
    alt: "Escudo indumentaria",
    descripcion: "Escudo moderno con 5 puntas en su diseño, presente en mucha indumentaria.",
  },
  {
    id: "escudo-2020",
    nombre: "",
    periodo: "2019 – 2020",
    src: "/museo/escudos/norm_2020.png",
    alt: "Escudo 60 años",
    descripcion: "Escudo en conmemoración a los 60 años del club.",
  },
  {
    id: "escudo-2025",
    nombre: "",
    periodo: "2020 – actual",
    src: "/museo/escudos/norm_2025.png",
    alt: "Escudo actual",
    descripcion: "Escudo con el diseño moderno utilizado actualmente.",
  },
];

export const camisetas = [
  {    id: "camiseta-1955",
       titulo: "Elaboración propia",
       temporada: "1955",
       tipo: "Titular",
        src: "/museo/camisetas/1955.png",
        alt: "Camiseta titular 1955",
        descripcion: "Camiseta titular",
        historia: "La primer camiseta del club utilizada en un partido de primera división.",
        hitos: [],
  },
  {
    id: "camiseta-1991",
    titulo: "Elaboración propia",
    temporada: "1991",
    tipo: "Titular",
    src: "/museo/camisetas/1991.png",
    alt: "Camiseta titular 1991",
    descripcion: "Camiseta titular",
    historia: "Diseño clásico de la época, aún sin utilizar el escudo generalmente.",
    hitos: [], // Sin títulos ese año
  },
  {
    id: "camiseta-1998",
    titulo: "ED Indumentaria",
    temporada: "1998",
    tipo: "Titular",
    src: "/museo/camisetas/1998v2.png",
    alt: "Camiseta titular 1998",
    descripcion: "Camiseta principalmente utilizada durante Torneo del Argentino B 1997/98.",
    hitos: [],
  },
  {
    id: "camiseta-2001",
    titulo: "C Sport",
    temporada: "2001",
    tipo: "Titular",
    src: "/museo/camisetas/2001.png",
    alt: "Camiseta titular 2001",
    descripcion: "Camiseta del equipo campeón entrerriano 2001.",
    hitos: [
      { titulo: "Regionalito", tipo: "copa" }
    ],
  },
  {
    id: "camiseta-2004",
    titulo: "C Sport",
    temporada: "2004",
    tipo: "Titular",
    src: "/museo/camisetas/2004.png",
    alt: "Camiseta titular 2004",
    descripcion: "El equipo con figuras como Galizzi y Vecchio se consagró campeón con esta reliquia.",
    hitos: [
      { titulo: "Torneo Oficial", tipo: "copa" }
    ],
  },
  {
    id: "camiseta-2011",
    titulo: "Sports 2000",
    temporada: "2011",
    tipo: "Titular",
    src: "/museo/camisetas/2011.png",
    alt: "Camiseta titular 2011",
    descripcion: "Camiseta clásica de Barrio Norte a comienzos de los 2010s.",
    hitos: [],
  },
  {
    id: "camiseta-2012",
    titulo: "Sports 2000",
    temporada: "2012",
    tipo: "Titular",
    src: "/museo/camisetas/2012.png",
    alt: "Camiseta titular 2012",
    descripcion: "Camiseta titular presentada formalmente en un evento del club, utilizada durante 2012 y 2013.",
    hitos: [],
  },
  
  {
    id: "camiseta-2012-sup",
    titulo: "Sports 2000",
    temporada: "2012",
    tipo: "Suplente",
    src: "/museo/camisetas/2012-sup.png",
    alt: "Camiseta suplente 2012",
    descripcion: "Camiseta suplente presentada formalmente en un evento del club, utilizada durante 2012 y 2013.",
    hitos: [],
  },
  {
    id: "camiseta-2014",
    titulo: "Sports 2000",
    temporada: "2014",
    tipo: "Titular",
    src: "/museo/camisetas/2014_vf.png",
    alt: "Camiseta titular 2014",
    descripcion: "Camiseta titular similar a la de años anteriores.",
    hitos: [],
  },
  {
    id: "camiseta-2014-sup",
    titulo: "Sports 2000",
    temporada: "2014",
    tipo: "Suplente",
    src: "/museo/camisetas/2014-sup.png",
    alt: "Camiseta suplente 2014",
    descripcion: "Esta camiseta fue utilizada varios años en las inferiores.",
    hitos: [],
  },
  {
    id: "camiseta-2015",
    titulo: "Sports 2000",
    temporada: "2015",
    tipo: "Titular",
    src: "/museo/camisetas/2015_vf.png",
    alt: "Camiseta titular 2015",
    descripcion: "Camiseta clásica a bastones blancos.",
    hitos: [],
  },
  
  {
    id: "camiseta-2015-sup",
    titulo: "Sports 2000",
    temporada: "2015",
    tipo: "Suplente",
    src: "/museo/camisetas/2015-sup_vf.png",
    alt: "Camiseta suplente 2015",
    descripcion: "Camiseta suplente del año 2015.",
    hitos: [],
  },
  {
    id: "camiseta-2016",
    titulo: "Sports 2000",
    temporada: "2016",
    tipo: "Titular",
    src: "/museo/camisetas/2016.png",
    alt: "Camiseta titular 2016",
    descripcion: "Camiseta titular con la que Barrio Norte obtiene la primera rueda del Torneo Oficial 2016.",
    hitos: [],
  },
  {
    id: "camiseta-2016-sup",
    titulo: "Sports 2000",
    temporada: "2016",
    tipo: "Suplente",
    src: "/museo/camisetas/2016-sup.png",
    alt: "Camiseta suplente 2016",
    descripcion: "Camiseta suplente con la que Barrio Norte obtiene la primera rueda del Torneo Oficial 2016.",
    hitos: [],
  },
  ,
  {
    id: "camiseta-2017",
    titulo: "Kion",
    temporada: "2017",
    tipo: "Titular",
    src: "/museo/camisetas/2017.png",
    alt: "Camiseta titular 2017",
    descripcion: "Camiseta con la que Barrio Norte disputa la Copa Entre Ríos 2017, quedando subcampeón.",
    hitos: [],
  },
  {
    id: "camiseta-2017-sup",
    titulo: "Kion",
    temporada: "2017",
    tipo: "Suplente",
    src: "/museo/camisetas/2017-sup.png",
    alt: "Camiseta suplente 2017",
    descripcion: "Camiseta suplente con la que Barrio Norte disputa la Copa Entre Ríos 2017, quedando subcampeón.",
    hitos: [],
  },
  {
    id: "camiseta-2019",
    titulo: "Sports 2000",
    temporada: "2019",
    tipo: "Titular",
    src: "/museo/camisetas/2019.png",
    alt: "Camiseta titular 2019",
    descripcion: "Camiseta titular utilizada durante 2019 y 2020.",
    hitos: [],
  },
  {
    id: "camiseta-2019-sup",
    titulo: "Sports 2000",
    temporada: "2019",
    tipo: "Suplente",
    src: "/museo/camisetas/2019-sup.png",
    alt: "Camiseta suplente 2019",
    descripcion: "Camiseta suplente utilizada durante 2019 y 2020.",
    hitos: [],
  },
  {
    id: "camiseta-2021",
    titulo: "Kion",
    temporada: "2021",
    tipo: "Titular",
    src: "/museo/camisetas/2021.png",
    alt: "Camiseta titular 2021",
    descripcion: "Camiseta titular",
    historia: "Camiseta titular con la cual la dupla Caminos-Villabona obtiene el título del Torneo Oficial 2021/22, el primero disputado después de la pandemia de Covid 19.",
    hitos: [
      { titulo: "Torneo Oficial", tipo: "copa" }
    ],
  },
  {
    id: "camiseta-2021-sup",
    titulo: "Kion",
    temporada: "2021",
    tipo: "Suplente",
    src: "/museo/camisetas/2021-sup.png",
    alt: "Camiseta suplente 2021",
    descripcion: "Camiseta suplente",
    historia: "Camiseta suplente con la cual la dupla Caminos-Villabona obtiene el título del Torneo Oficial 2021/22, el primero disputado después de la pandemia de Covid 19.",
    hitos: [
      { titulo: "Torneo Oficial", tipo: "copa" }
    ],
  },
  {
    id: "camiseta-2022",
    titulo: "Kion",
    temporada: "2022",
    tipo: "Titular",
    src: "/museo/camisetas/2022.png",
    alt: "Camiseta titular 2022",
    descripcion: "Camiseta titular",
    historia: "Barrio Norte sale campeón por segunda vez en el año, con un plantel de ensueño a cargo de la dupla técnica Caminos-Villabona.",
    hitos: [
      { titulo: "Torneo Oficial", tipo: "copa" }
    ],
  },
  {
    id: "camiseta-2022-sup",
    titulo: "Kion",
    temporada: "2022",
    tipo: "Suplente",
    src: "/museo/camisetas/2022-sup-pro.png",
    alt: "Camiseta suplente 2022",
    descripcion: "Camiseta suplente",
    historia: "Barrio Norte sale campeón por segunda vez en el año, con un plantel de ensueño a cargo de la dupla técnica Caminos-Villabona.",
    hitos: [
      { titulo: "Torneo Oficial", tipo: "copa" }
    ],
  },
  {
    id: "camiseta-2023",
    titulo: "Kion",
    temporada: "2023",
    tipo: "Titular",
    src: "/museo/camisetas/2023.png",
    alt: "Camiseta titular 2023",
    descripcion: "Camiseta titular",
    historia: "Barrio Norte como vigente bicampeón gualeyo no logra meterse en el Petit Torneo, quedando fuera de competencia de manera temprana. Se disputa la Supercopa Entre Ríos llegando hasta 16avos.",
    hitos: [],
  },
  {
    id: "camiseta-2023-sup",
    titulo: "Kion",
    temporada: "2023",
    tipo: "Suplente",
    src: "/museo/camisetas/2023-sup.png",
    alt: "Camiseta suplente 2023",
    descripcion: "Camiseta suplente",
    historia: "Barrio Norte como vigente bicampeón gualeyo no logra meterse en el Petit Torneo, quedando fuera de competencia de manera temprana. Se disputa la Supercopa Entre Ríos llegando hasta 16avos.",
    hitos: [],
  },
  {
    id: "camiseta-2024",
    titulo: "Kion",
    temporada: "2024",
    tipo: "Titular",
    src: "/museo/camisetas/2024.png",
    alt: "Camiseta titular 2024",
    descripcion: "Camiseta titular",
    historia: "Un año de grandes hazañas, donde el equipo comandado por el 'Beto' García vence por penales a Central para ganar el Torneo Preparación. Luego en el Oficial Barrio Norte se mete por la ventana al Petit Torneo alzándose luego de manera agónica con el título.",
    hitos: [
      { titulo: "Torneo Preparación", tipo: "copa" },
      { titulo: "Torneo Oficial", tipo: "copa" }
    ],
  },
  {
    id: "camiseta-2024-sup",
    titulo: "Kion",
    temporada: "2024",
    tipo: "Suplente",
    src: "/museo/camisetas/2024-sup.png",
    alt: "Camiseta suplente 2024",
    descripcion: "Camiseta suplente",
    historia: "Un año de grandes hazañas, donde el equipo comandado por el 'Beto' García vence por penales a Central para ganar el Torneo Preparación. Luego en el Oficial Barrio Norte se mete por la ventana al Petit Torneo alzándose luego de manera agónica con el título.",
    hitos: [
      { titulo: "Torneo Preparación", tipo: "copa" },
      { titulo: "Torneo Oficial", tipo: "copa" }
    ],
  },
  {
    id: "camiseta-2025",
    titulo: "Kion",
    temporada: "2025",
    tipo: "Titular",
    src: "/museo/camisetas/2025-tit-pro_vf.png",
    alt: "Camiseta titular 2025",
    descripcion: "Camiseta titular",
    historia: "Se alcanza la fase del Petit Torneo, tras una temporada de altibajos 'Beto' García deja el mando del Norte.",
    hitos: [],
  },
  {
    id: "camiseta-2025-sup",
    titulo: "Kion",
    temporada: "2025",
    tipo: "Suplente",
    src: "/museo/camisetas/2025-sup-pro_vf.png",
    alt: "Camiseta suplente 2025",
    descripcion: "Camiseta suplente",
    historia: "Se alcanza la fase del Petit Torneo, tras una temporada de altibajos 'Beto' García deja el mando del Norte.",
    hitos: [],
  },
  {
    id: "camiseta-2026",
    titulo: "Kion",
    temporada: "2026",
    tipo: "Titular",
    src: "/museo/camisetas/2026.png",
    alt: "Camiseta titular 2026",
    descripcion: "Camiseta titular",
    historia: "Camiseta de la actual temporada 2026.",
    hitos: [],
  },
  {
    id: "camiseta-2026-sup",
    titulo: "Kion",
    temporada: "2026",
    tipo: "Suplente",
    src: "/museo/camisetas/2026-sup.png",
    alt: "Camiseta suplente 2026",
    descripcion: "Camiseta suplente",
    historia: "Camiseta de la actual temporada 2026.",
    hitos: [],
  },
];